# Use multi stage build for install cli tools
FROM ghcr.io/opentofu/opentofu:minimal AS tofu
FROM ghcr.io/terraform-linters/tflint:latest AS tflint

FROM ubuntu:24.04

COPY --from=tofu /usr/local/bin/tofu /usr/local/bin/tofu
COPY --from=tflint /usr/local/bin/tflint /usr/local/bin/tflint

RUN apt-get update && apt-get install -y \
    curl \
    wget \
    git \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

RUN tofu --version && \
    tflint --version

WORKDIR /app

CMD ["/bin/bash"]
